version: '3.9'

services:
  postgres:
    container_name: 'task-tracker-postgres'
    image: postgres:alpine3.20
    restart: always
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_DB: task-tracker-db
    ports:
      - '5433:5432'

  rabbitmq:
    container_name: 'task-tracker-rabbitmq'
    image: bitnami/rabbitmq:3.12.0
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_USERNAME: task-tracker
      RABBITMQ_PASSWORD: 12345

  redis:
    container_name: 'task-tracker-redis'
    image: redis:7.2.5-alpine
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_storage:/data

volumes:
    db_storage:
    redis_storage:



